// <auto-generated />
using System;
using Cadence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cadence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CadenceDbContext))]
    partial class CadenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cadence.Domain.Activities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageCadenceRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<double>("AveragePaceSecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("AveragePowerWatts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscardedSampleCount")
                        .HasColumnType("integer");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("ElapsedTime")
                        .HasColumnType("interval");

                    b.Property<double>("ElevationGainMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("ElevationLossMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("GradeAdjustedPaceSecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("MovingTime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LineString>("Route")
                        .HasColumnType("geometry(LineString, 4326)");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<LineString>("SimplifiedRoute")
                        .HasColumnType("geometry(LineString, 4326)");

                    b.Property<string>("SourceChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Route")
                        .HasDatabaseName("IX_Activities_Route");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Route"), "gist");

                    b.HasIndex("AthleteId", "SourceChecksum")
                        .IsUnique()
                        .HasDatabaseName("IX_Activities_AthleteId_SourceChecksum");

                    b.HasIndex("AthleteId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Activities_AthleteId_StartedAt");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Activities.ActivitySample", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<int?>("CadenceRpm")
                        .HasColumnType("integer");

                    b.Property<double>("CumulativeDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("double precision");

                    b.Property<int?>("HeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<int?>("PowerWatts")
                        .HasColumnType("integer");

                    b.Property<double?>("SpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActivityId", "Sequence");

                    b.ToTable("ActivitySamples", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Activities.ActivitySplit", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<double>("ElevationGainMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("GradeAdjustedPaceSecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<double>("PaceSecondsPerKm")
                        .HasColumnType("double precision");

                    b.HasKey("ActivityId", "Number");

                    b.ToTable("ActivitySplits", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Athletes.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComputedColumnSql("lower(\"Email\")", true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("WeightKilograms")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_Athletes_Email_Lower");

                    b.ToTable("Athletes", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Coaching.CoachingReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("_findings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Findings");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "GeneratedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CoachingReports_AthleteId_GeneratedAt");

                    b.ToTable("CoachingReports", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Activities.Activity", b =>
                {
                    b.HasOne("Cadence.Domain.Athletes.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cadence.Domain.Activities.ActivitySample", b =>
                {
                    b.HasOne("Cadence.Domain.Activities.Activity", null)
                        .WithMany("Samples")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cadence.Domain.Activities.ActivitySplit", b =>
                {
                    b.HasOne("Cadence.Domain.Activities.Activity", null)
                        .WithMany("Splits")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cadence.Domain.Coaching.CoachingReport", b =>
                {
                    b.HasOne("Cadence.Domain.Athletes.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cadence.Domain.Activities.Activity", b =>
                {
                    b.Navigation("Samples");

                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
